api/urls.py
from django.conf.urls import url
from django.urls import include
from rest_framework.routers import DefaultRouter

from api.api import BudgetViewset
from api.api_admin import AdminViewset
from api.students.angola_bernardo import AngolaBernardoViewset
from api.students.angola_estima import AngolaEstimaViewset
from api.students.angola_lupossa import AngolaLupossaViewset


router = DefaultRouter()

router.register(r'api-admin', AdminViewset, basename='api_admin')
router.register(r'budgets', BudgetViewset, basename='budgets')

# Students
router.register(r'angola-estima', AngolaEstimaViewset, basename='angola_estima_api')
router.register(r'angola-lupossa', AngolaLupossaViewset, basename='angola_lupossa_api')
router.register(r'angola-bernardo', AngolaBernardoViewset, basename='angola_bernardo_api')



urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls'))
]

config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


def sentry_debug_view(request):
    division_by_zero = 1 / 0


urlpatterns = i18n_patterns(
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('cso_admin/', admin.site.urls),

    prefix_default_language=True
)

urlpatterns += [
    path('api/', include('api.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('sentry-debug/', sentry_debug_view),

    path('', include('frontend.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

frontend/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from frontend.student_views import AngolaIndex
from frontend.student_views.angola_bernardo import TotalExpensePerYear
from frontend.student_views.angola_estima import ChartBudgetYearView
from frontend.student_views.angola_lupossa import BudgetCountryYear
from frontend.views import IndexView, CountryView, CountriesExpensesView, ExpensesAndRevenues, TestView


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('comparativo-despesas/', CountriesExpensesView.as_view(), name='countries-expenses'),
    path('teste/', TestView.as_view(), name='test'),
    path('dataviz/', TemplateView.as_view(template_name="frontend/chart_sample.htm"), name='dataviz'),
    # Students
    path('students/angola/', AngolaIndex.as_view(), name='chart-budget'),
    path('students/angola/chart-budget-per-year-and-currency/', ChartBudgetYearView.as_view(), name='chart-budget'),
    path('students/angola/budget_country_year/', BudgetCountryYear.as_view(), name='budget_country_year'),
    path('students/angola/total-expense-per-year/', TotalExpensePerYear.as_view(), name='total-expense-per-year'),

    path('<slug>/', CountryView.as_view(), name='country-details'),
    path('<slug>/despesas-e-receitas/', ExpensesAndRevenues.as_view(), name='despesas-e-receitas'),
    path('avatar/', include('avatar.urls')),
]

project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    
]

frontend/forms.py
from django import forms

from apps.budget.models import Budget
from apps.geo.models import Country
from config.settings import CURRENCY_CHOICES


def year_choices():
    return list(Budget.objects.order_by('year').distinct('year').values_list('year', 'year'))


class BudgetPerYearForm(forms.Form):
    base_currency = forms.ChoiceField(choices=CURRENCY_CHOICES)
    year = forms.ChoiceField(choices=year_choices())


class YearPercentForm(forms.Form):
    country = forms.ModelChoiceField(queryset=Country.objects.all())
    year = forms.ChoiceField(choices=year_choices())

frontend/views.py
import json

from django.conf import settings
from django.shortcuts import render
from django.views import View
from django.views.generic.detail import SingleObjectMixin

from apps.geo.models import Country

from frontend.tutorial import COUNTRY_DETAILS_TUTORIAL, INDEX_DIMENSIONS


class IndexView(View):
    def get(self, request):
        ctx = {
            'countries': Country.objects.all(),
            'index_dimensions': INDEX_DIMENSIONS
        }
        return render(request, 'frontend/index.html', context=ctx)


class CountryView(SingleObjectMixin, View):
    model = Country

    def get(self, request):
        country = self.get_object()
        base_qs = country.budgets.filter(is_active=True)
        budgets = base_qs.order_by('year')
        last_budget = base_qs.order_by('year').select_related('summary').last()
        summary = last_budget.summary

        default_budget_account = 'expenses'
        default_group = 'functional' if summary and summary.expense_functional_budget else 'organic'

        budgets_serialized = {}
        for b in budgets:
            budgets_serialized[b.id] = {
                'id': b.id,
                'year': b.year,
                'available_groups': b.get_available_groups(),
                'available_budget_accounts': b.get_available_budget_accounts(),
                'expense_functional_budget': b.summary.expense_functional_budget,
                'expense_organic_budget': b.summary.expense_organic_budget,
                'revenue_nature_budget': b.summary.revenue_nature_budget,
                'revenue_source_budget': b.summary.revenue_source_budget,
            }

        ctx = {
            'default_budget_account': default_budget_account,
            'default_group': default_group,
            'country': country,
            'budgets': budgets,
            'last_budget': last_budget,
            'budgets_serialized': json.dumps(budgets_serialized),
            'treemap_colors_map': json.dumps(settings.TREEMAP_EXECUTION_COLORS_HOVER),
            'tutorial': COUNTRY_DETAILS_TUTORIAL
        }
        return render(request, 'frontend/country-details.html', context=ctx)


class CountriesExpensesView(View):
    def get(self, request):
        return render(request, 'frontend/countriesExpenses.html', context=None)


class TestView(View):
    def get(self, request):
        ctx = {
            'countries': Country.objects.all()
        }
        return render(request, 'frontend/teste.html', context=ctx)


class ExpensesAndRevenues(View, ):
    def get(self, request, *args, **kwargs):
        cn = {
            "country": Country.objects.get(slug=self.kwargs.get("slug"))
        }
        return render(request, 'frontend/expenses-and-revenues.html', context=cn)

frontend/templates/frontend/base.html
{% load i18n static custom_tags %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}{% get_countries as all_countries %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
    <head>
        <title>{% block title %}{% trans "PALOP-TL CSO online budget platform" %}{% endblock %}</title>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Roboto&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static "css/font.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/simple-grid.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/frontend.css" %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" type="text/css" href="{% static "external/introjs/introjs.min.css" %}">

        <script src="{% static 'external/jquery-3.5.1.min.js' %}"></script>
        <script src="{% static 'external/introjs/intro.min.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.12/handlebars.min.js"></script>
        <script src="{% static 'js/common.js' %}"></script>
        <script src="{% static 'js/handlebars-helpers.js' %}"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $('.language-selector-form').find('a').on('click', function(ev){
                    ev.preventDefault();
                    var $form = $(this).closest('form');
                    var language = $(this).data('language_code');
                    $form.find('input[name="language"]').val(language);
                    $form.submit();
                })
            })
        </script>
        {% block extrastyle %}{% endblock %}
        {% block extrahead %}{% endblock %}
    </head>

    <body>

    {% block header %}
        <div class="header">
            <div class="container">
                <div class="row upper-row middle">
                    <div class="col-6">
                        <div class="row logos">
                            <div class="col-6 ml-0">
                                <img src="{% static 'img/logo-propaloptl-pt.png' %}" class="logo-propaloptl" alt="Logo Pro PALOP-TL ISC" />
                            </div>
                            <div class="col-6">
                                <img src="{% static 'img/logo-paloptl-ue.png' %}" class="logo-ue" alt="Logo PALOP-TL UE" />
                            </div>
                        </div>
                    </div>
                    <div class="col-6 right">
                        {% include 'frontend/language-selector.component.html' %}
                    </div>
                </div>
            </div>
            <hr />
            <div class="container">
                <div class="row bottom-row middle">
                    <div class="col-11">
                        <h1>
                            <a href="{% url 'index' %}">
                                {% blocktrans trimmed %}
                                <strong>PALOP-TL</strong> Civil Society <strong>Online Budget Platform</strong>
                                {% endblocktrans %}
                            </a>
                        </h1>
                    </div>
                    <div class="col-1 right">
                        <div class="menu">
                            <div class="dropbtn">
                                <div></div>
                                <div></div>
                                <div></div>
                            </div>
                            <div class="dropdown-content">
                                <div class="short-description">
                                    {% blocktrans %}Choose a country to<br>understand its budget{% endblocktrans %}
                                </div>
                                {% for country in all_countries %}
                                    <a href="{% url 'country-details' country.slug %}">
                                        <img src="{{ country.flag.url }}"/> {{ country.name }}
                                    </a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock header %}

    {% block content %}{% endblock content %}

    {% block footer %}
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="countries">
                        {% for country in all_countries %}
                            <a href="{% url 'country-details' country.slug %}" >
                                <img src="{{ country.flag.url }}" />
                                <span>{{ country.name }}</span>
                            </a>
                        {% endfor %}
                        </div>
                    </div>
                </div>

                <div class="row sponsors">
                    <div class="col-7 first-col">
                        <div class="row upper-row middle logos">
                            <div class="col-6 ml-0">
                                <img src="{% static 'img/logo-propaloptl-pt.png' %}" class="logo-propaloptl" alt="Logo Pro PALOP-TL ISC" />
                            </div>
                            <div class="col-6">
                                <img src="{% static 'img/logo-paloptl-ue.png' %}" class="logo-ue" alt="Logo PALOP-TL UE" />
                            </div>
                        </div>
                        <div class="row bottom-row middle">
                            <div class="col-5 ml-0">
                                <img class="logos-ods" src="{% static 'img/logos_ods.png' %}" />
                            </div>
                        </div>
                    </div>
                    <div class="col-5">
                        <div class="disclaimer">
                            {% blocktrans trimmed %}
                                The Online Platform for PALOP and Timor-Leste Civil Society Organizations for Budget
                                Simplification and Analysis was produced by Pro PALOP-TL ISC, and co-financed by the
                                European Union and the United Nations Development Programme.<br>
                                Its contents are the sole responsibility of Pro PALOP-TL ISC and can in no way be used
                                to reflect the positions of the European Union.<br>
                                The opinions expressed on this platform are those of the authors alone and do not
                                necessarily represent the views of the United Nations, the United Nations
                                Development Programme, or the United Nations Member States.
                            {% endblocktrans %}
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            <div class="container">
                <div class="row last-line middle">
                    <div class="col-3">{% include 'frontend/language-selector.component.html' %}</div>
                    <div class="col-6 center">{% trans "2020 ©PALOP-TL ISC All rights reserved" %}</div>
                    <div class="col-3 right social">
                        <a target="_blank" href="{% get_social_network_url 'facebook' %}"><img src="{% static 'img/icon_facebook.png' %}" alt="facebook icon" /></a>
                        <a target="_blank" href="{% get_social_network_url 'youtube' %}"><img src="{% static 'img/icon_youtube.png' %}" alt="youtube icon" /></a>
                        <a target="_blank" href="{% get_social_network_url 'twitter' %}"><img src="{% static 'img/icon_twitter.png' %}" alt="twitter icon" /></a>
                        <a target="_blank" href="{% get_social_network_url 'instagram' %}"><img src="{% static 'img/icon_instagram.png' %}" alt="instagram icon" /></a>
                    </div>
                </div>
            </div>
        </div>

    {% endblock %}
    <script src="{% static 'js/avatar_index.js' %}"></script>
    </body>
</html>

frontend/templates/frontend/chart-budget-per-year-and-currency.html
{% extends 'frontend/base.html' %}
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block extrastyle %}
<!-- Styles -->
<style>
    #chartdiv {
        width: 80%;
        height: 500px;
    }
</style>

<!-- Resources -->
<script src="https://cdn.amcharts.com/lib/4/core.js"></script>
<script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
<script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>
{% endblock %}

{% block extrahead %}

<script type="text/javascript">
    function get_api_data(year, base_currency){
        $.get('/api/budgets/summary_budget_per_year_all_country/?year='+year+'&base_currency='+base_currency, function (data) {
            //console.table(data);
            chart.data = data;
        });
    }

    $(document).ready(function () {
        //Bind
        $(document).on('change', '#id_year', function(){
            get_api_data($(this).val(), $('#id_base_currency').val());
        });

        //Bind
        $(document).on('change', '#id_base_currency', function(){
            get_api_data($('#id_year').val(), $(this).val());
        });

        //init
        $('#id_year').trigger('change');
        $('#id_base_currency').trigger('change');
    });

    var chart;
    am4core.ready(function () {

        // Themes begin
        am4core.useTheme(am4themes_animated);
        // Themes end

        chart = am4core.create("chartdiv", am4charts.XYChart);
        chart.padding(20, 20, 20, 20);

        chart.numberFormatter.bigNumberPrefixes = [
            {"number": 1e+3, "suffix": "K"},
            {"number": 1e+6, "suffix": "Mi"},
            {"number": 1e+9, "suffix": "Bi"},
            {"number": 1e+12, "suffix": "Tri"},
            {"number": 1e+15, "suffix": "Qua"},
            {"number": 1e+18, "suffix": "E"},
            {"number": 1e+21, "suffix": "Z"},
            {"number": 1e+24, "suffix": "Y"}
        ]

        chart.numberFormatter.numberFormat = "#,#.a";

        var categoryAxis = chart.yAxes.push(new am4charts.CategoryAxis());
        categoryAxis.renderer.grid.template.location = 0;
        categoryAxis.dataFields.category = "country";
        categoryAxis.renderer.minGridDistance = 1;
        categoryAxis.renderer.inversed = true;
        categoryAxis.renderer.grid.template.disabled = true;

        var valueAxis = chart.xAxes.push(new am4charts.ValueAxis());
        valueAxis.min = 0;

        var series = chart.series.push(new am4charts.ColumnSeries());
        series.dataFields.categoryY = "country";
        series.dataFields.valueX = "budget_euro";
        series.tooltipText = "{valueX.value}"
        series.columns.template.strokeOpacity = 0;
        series.columns.template.column.cornerRadiusBottomRight = 5;
        series.columns.template.column.cornerRadiusTopRight = 5;

        var labelBullet = series.bullets.push(new am4charts.LabelBullet())
        labelBullet.label.horizontalCenter = "left";
        labelBullet.label.dx = 10;
        labelBullet.label.text = "{values.valueX.workingValue.formatNumber('#.0as')}";
        labelBullet.locationX = 1;

        // as by default columns of the same series are of the same color, we add adapter which takes colors from chart.colors color set
        series.columns.template.adapter.add("fill", function (fill, target) {
            return chart.colors.getIndex(target.dataItem.index);
        });

        categoryAxis.sortBySeries = series;
        

    }); // end am4core.ready()
</script>

{% endblock extrahead %}

{% block content %}
<div class="row">
    <script type="text/javascript">


    </script>
    <div class="left">

        {{ form }}
    </div>
    <br>

    <!-- HTML -->
    <div class="col-3"></div>
    <div class="col-6 chart-wrapper" id="chartdiv"></div>
    <div class="col-3"></div>

</div>

{% endblock %}

frontend/templates/frontend/chart.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/chart.css' %}">

<script src="https://cdn.amcharts.com/lib/4/core.js"></script>
<script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
<script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>
<script src="{% static 'js/chart.js' %}"></script>

{% endblock extrahead %}

{% block content %}
<!-- HTML -->
<div>
    <button class="ano">2018</button>
    <button class="ano">2019</button>
    <button class="ano">2020</button>
    <button class="ano">2021</button>
</div>
<div id="chartdiv"></div>
{% endblock content %}

frontend/templates/frontend/countriesExpenses.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/countriesExpenses.css' %}">

<script src="https://cdn.amcharts.com/lib/4/core.js"></script>
<script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
<script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>
<script src="{% static 'js/countriesExpenses.js' %}"></script>

{% endblock extrahead %}

{% block content %}
<hr />
<div class="page-countries-expenses">
    <div class="historical-wrapper viz-wrapper">
        <div class="loading">Carregando dados<br><img src="{% static 'img/loading-front.gif' %}" /></div>
        <h4 class="historical-title">
            Dotação das principais despesas<br>funcionais em relação ao orçamento<br>
            <span class="year"></span>
        </h4>
        <div class="container">
            <div class="row breadcrumb-row" id="anchor-{{ visualization }}">
                <div class="col-12 right budget-account-selector-row">
                    <div class="year-selector">
                        <a>2016
                        </a><a>2017
                        </a><a>2018
                        </a><a>2019
                        </a><a>2020
                        </a><a>2021</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div id="chartdiv"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 right disclaimer">
                    *Países que não possuem valores sobre alguma despesa na legenda, não disponibilizaram as respectivas
                    dotações para aquela despesa no ano selecionado.<br>
                    **Países que não constam no gráfico não disponibilizaram nenhuma informação sobre despesas
                    funcionais para o ano selecionado.
                </div>
            </div>
        </div>
    </div>

    {% include 'frontend/transparency-text.component.html' %}
</div>
{% endblock content %}

frontend/templates/frontend/expense-and-revenue.html
{% extends 'frontend/base.html' %}
{% load static %}

{% block extrahead %}
<!-- Resources -->
<script src="https://cdn.amcharts.com/lib/4/core.js"></script>
<script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
<script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>

<link rel="stylesheet" type="text/css" href="{% static "css/country-expense-revenue.css" %}">

{% endblock extrahead %}

{% block content %}
<div class="block">


    <h1 id="name"> Hello {{ country.name }} </h1>

    <img class="block__flag" id="flag" src="{{ country.flag.url }}" alt="{{ country.slug }} flag"/>



    <!-- HTML -->
    <div id="chartdiv"></div>

    <script src="{% static 'js/country-expenses-revenue.js' %}"></script>

    <ul class="block__list">
        {% for country in countries %}
        <li class="block__list__item" onclick="GetExpenseAndRevenue({{ country.id }})"><a href="{% url 'country-expense-revenue' country.slug %}">{{ country.name }}</a></li>
        {% endfor %}
    </ul>

    <script>
        GetExpenseAndRevenue({{ country.id }});
    </script>
</div>

{% endblock %}

frontend/templates/frontend/expenses_by_country.html
{% extends 'frontend/base.html' %}
{% load static %}

{% block content %}
    <h2>Expenses by countries</h2>
    <div id="group-button-year">
        <a href="#">2015</a>
        <button class="year">2016</button>
        <button class="year">2017</button>
        <button class="year">2018</button>
        <button class="year">2019</button>
        <button class="year">2020</button>
        <button class="year">2021</button>
    </div>
    <div id="list_countries"></div>
    <div id="chartdiv"></div>

{% endblock content%}

{% block extrahead %}
    <!-- Resources -->
    <script src="https://cdn.amcharts.com/lib/4/core.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>
    <script src="{% static 'js/expenses_by_country.js' %}"></script>
    <style>
    #chartdiv {
      width: 100%;
      height: 500px;
    }
    .year {
        background-color: white;
    }

    #group-button-year {
            margin-right: 15px;
            text-align: right;
    }

    </style>
{% endblock %}

frontend/templates/frontend/expenses_revenues.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block extrahead %}
    <script src="https://cdn.amcharts.com/lib/4/core.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
        }
        #chartdiv {
          width: 100%;
          height: 500px;
        }
        [aria-labelledby=id-66-title]{
            display: none;
        }
    </style>
{% endblock extrahead %}

{% block content %}
    <div class="page-country-detail">
    {% with bg_name="bg_"|add:country.slug|add:".png" %}
    <div class="country-name-wrapper" style="background-image: url('{% static 'img/'|add:bg_name %}');">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1>{{ country.name }}</h1>
                </div>
            </div>
        </div>
    </div>
    {% endwith %}
    <div class="flag-wrapper">
        <div class="row middle">
            <div class="col-2 mr-0">
                <img class="flag country" src="{{ country.flag.url }}" alt="{{ country.slug }} flag"  country_id="{{ country.id }}" cur="{{ country.currency }}"/>
            </div>
        </div>
    </div>
  <div class="container">
            <div class="row breadcrumb-row">
                <div class="col-12 right budget-account-selector-row">
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div id="chartdiv"></div>
                </div>
            </div>
        </div>
</div>
    <script src="{% static 'js/expensesRevenues.js' %}"></script>
{% endblock content %}

frontend/templates/frontend/teste.html
{% extends 'frontend/base.html' %}

{% block content %}
    <h1>Hello world!</h1>

    {% for c in countries %}
        <a href="/{{ c.slug }}">{{ c.name }} - {{ c.currency }} </a><br/>
    {% endfor %}
{% endblock %}

frontend/templates/frontend/teste_view.html
{% extends 'frontend/base.html' %}
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block extrastyle %}
<!-- Styles -->
<style>
    #chartdiv {
        width: 80%;
        height: 500px;
    }
</style>

<!-- Resources -->
<script src="https://cdn.amcharts.com/lib/4/core.js"></script>
<script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
<script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>
{% endblock %}

{% block extrahead %}

<script type="text/javascript">
    function get_api_data(year, base_currency){
        $.get('/api/budgets/summary_budget_per_year_all_country/?year='+year+'&base_currency='+base_currency, function (data) {
            //console.table(data);
            chart.data = data;
        });
    }

    $(document).ready(function () {
        //Bind
        $(document).on('change', '#id_year', function(){
            get_api_data($(this).val(), $('#id_base_currency').val());
        });

        //Bind
        $(document).on('change', '#id_base_currency', function(){
            get_api_data($('#id_year').val(), $(this).val());
        });

        //init
        $('#id_year').trigger('change');
        $('#id_base_currency').trigger('change');
    });

    var chart;
    am4core.ready(function () {

        // Themes begin
        am4core.useTheme(am4themes_animated);
        // Themes end

        chart = am4core.create("chartdiv", am4charts.XYChart);
        chart.padding(20, 20, 20, 20);

        chart.numberFormatter.bigNumberPrefixes = [
            {"number": 1e+3, "suffix": "K"},
            {"number": 1e+6, "suffix": "Mi"},
            {"number": 1e+9, "suffix": "Bi"},
            {"number": 1e+12, "suffix": "Tri"},
            {"number": 1e+15, "suffix": "Qua"},
            {"number": 1e+18, "suffix": "E"},
            {"number": 1e+21, "suffix": "Z"},
            {"number": 1e+24, "suffix": "Y"}
        ]

        chart.numberFormatter.numberFormat = "#,#.a";

        var categoryAxis = chart.yAxes.push(new am4charts.CategoryAxis());
        categoryAxis.renderer.grid.template.location = 0;
        categoryAxis.dataFields.category = "country";
        categoryAxis.renderer.minGridDistance = 1;
        categoryAxis.renderer.inversed = true;
        categoryAxis.renderer.grid.template.disabled = true;

        var valueAxis = chart.xAxes.push(new am4charts.ValueAxis());
        valueAxis.min = 0;

        var series = chart.series.push(new am4charts.ColumnSeries());
        series.dataFields.categoryY = "country";
        series.dataFields.valueX = "budget_euro";
        series.tooltipText = "{valueX.value}"
        series.columns.template.strokeOpacity = 0;
        series.columns.template.column.cornerRadiusBottomRight = 5;
        series.columns.template.column.cornerRadiusTopRight = 5;

        var labelBullet = series.bullets.push(new am4charts.LabelBullet())
        labelBullet.label.horizontalCenter = "left";
        labelBullet.label.dx = 10;
        labelBullet.label.text = "{values.valueX.workingValue.formatNumber('#.0as')}";
        labelBullet.locationX = 1;

        // as by default columns of the same series are of the same color, we add adapter which takes colors from chart.colors color set
        series.columns.template.adapter.add("fill", function (fill, target) {
            return chart.colors.getIndex(target.dataItem.index);
        });

        categoryAxis.sortBySeries = series;
        /* chart.data = [
            {
                "country": "Facebook",
                "budget": 2255250000
            },
            {
                "country": "Google+",
                "budget": 430000000
            },
            {
                "country": "Instagram",
                "budget": 1000000000
            },
            {
                "country": "Pinterest",
                "budget": 246500000
            },
            {
                "country": "Reddit",
                "budget": 355000000
            },
            {
                "country": "TikTok",
                "budget": 500000000
            },
            {
                "country": "Tumblr",
                "budget": 624000000
            },
            {
                "country": "Twitter",
                "budget": 329500000
            },
            {
                "country": "WeChat",
                "budget": 1000000000
            },
            {
                "country": "Weibo",
                "budget": 431000000
            },
            {
                "country": "Whatsapp",
                "budget": 1433333333
            },
            {
                "country": "YouTube",
                "budget": 1900000000
            }
        ] */

    }); // end am4core.ready()
</script>

{% endblock extrahead %}

{% block content %}
<div class="row">
    <script type="text/javascript">


    </script>
    <div class="left">

        {{ form }}
    </div>
    <br>

    <!-- HTML -->
    <div class="col-3"></div>
    <div class="col-6 chart-wrapper" id="chartdiv"></div>
    <div class="col-3"></div>

</div>

{% endblock %}